# Generated by Django 3.2.20 on 2023-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('api_id', models.CharField(max_length=255)),
                ('api_hash', models.CharField(max_length=255)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
