# Generated by Django 3.2.20 on 2023-07-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_channel', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('access_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.channel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.member')),
            ],
            options={
                'unique_together': {('channel', 'member')},
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(through='marketing.ChannelMembers', to='marketing.Member'),
        ),
    ]
