# Generated by Django 3.2.20 on 2023-07-19 06:22

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[marketing.models.validate_weak_password]),
        ),
    ]
