# Generated by Django 3.2.20 on 2023-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_telegramaccount_phone_code_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='verification_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
