# Generated by Django 3.2.20 on 2023-07-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_telegramaccount_verification_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramaccount',
            name='phone_code_hash',
        ),
        migrations.RemoveField(
            model_name='telegramaccount',
            name='verification_code',
        ),
    ]
