# Generated by Django 3.2.20 on 2023-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20230717_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
