# Generated by Django 3.2.20 on 2023-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_telegramaccount_phone_code_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(),
        ),
    ]
