# Generated by Django 3.2.20 on 2023-07-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_channel_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='telegram_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='marketing.telegramaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(related_name='channels', through='marketing.ChannelMembers', to='marketing.Member'),
        ),
    ]
