# Generated by Django 3.2.20 on 2023-07-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_auto_20230717_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.BigIntegerField(),
        ),
    ]
